name: CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4.1.2

        - name: Run lint
          run: ./gradlew lintDebug

        - name: upload html test report
          run: actions/upload-artifact@v4.3.1
          with:
            name: index.html
            path: app/build/reports/lint-results-debug.html


