name: CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4.1.2

        - name: Setup Java JDK
          uses: actions/setup-java@v4.2.1
          with:
            java-version: 17
            distribution: 'temurin'

#        - name: Run lint
#          run: ./gradlew lintDebug
#
#        - name: Upload html test report
#          uses: actions/upload-artifact@v4.3.1
#          with:
#            name: lint.html
#            path: app/build/reports/lint-results-debug.html

  unit-test:
    needs: [lint]
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

#      - name: Setup Java JDK
#        uses: actions/setup-java@v4.2.1
#        with:
#          java-version: 17
#          distribution: 'temurin'
#
#      - name: Run unit test
#        run: ./gradlew test
#
#      - name: Upload unit test report
#        uses: actions/upload-artifact@v4.3.1
#        with:
#          name: unit_test_report
#          path: app/build/reports/tests/testDebugUnitTest/

  instrumentation-test:
    needs: [unit-test]
    name: Android test
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Android tests
        uses: amyu/setup-android@v4
        with:
          sdk-version: 33

      - name: Android tests2
        uses: ReactiveCircus/android-emulator-runner@v2.30.1
        with:
            api-level: 33
            script: ./gradlew connectedCheck

      - name: Upload android test report
        uses: actions/upload-artifact@v4.3.1
        with:
          name: android_test_report
          path: app/build/reports/androidTests/connected/


